development:
  adapter: mysql2
  database: autolab_development
  pool: 5
  username: root
  password: root
  host: localhost
  port: 3306
  variables:
    sql_mode: NO_ENGINE_SUBSTITUTION

test:
  adapter: mysql2
  database: autolab_test
  pool: 5
  username: root
  password: root
  host: localhost
  port: 3306
  variables:
    sql_mode: NO_ENGINE_SUBSTITUTION
